name: intravision
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  assets:

    - assets/fonts/
    - assets/icons/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/placeholders/
    - assets/i18n/ar.json
    - assets/i18n/en.json
    
  fonts:
    - family: IBMPlexArabic
      fonts:
        - asset: assets/fonts/IBMPlexArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexArabic-Thin.ttf
          weight: 100